global:
  scrape_interval: 1m
  scrape_timeout: 20s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: /api/v1/write
    static_configs:
      - targets:
        - 'localhost:9090'
  
  
  - job_name: 'postgres_exporter'
    scrape_interval: 1s

    honor_labels: true
    metrics_path: /metrics
    static_configs:
     - targets:
       - '172.28.31.113:9187'
       - '172.28.31.114:9187'

